name: Cypress Tests

on:
    pull_request:
      paths:
      - 'client-app/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: client-app 
          start: npm start
